### ISSUE TITLE
CORS broken for ajax?

### ISSUE THREAD

**Issue by yohanboniface** [komoot/photon#122]
Seem that we can't make ajax CORS request on photon.komoot.de anymore. Worked some days ago.

```
$ http --headers 'http://photon.komoot.de/api/?q=clichy%20sous%20bois&limit=5&lat=48.91685918861334&lon=2.555694580078125'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Nov 2014 15:42:39 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
```
Seems that we are missing the `Access-Control-Allow-Headers: X-Requested-With` header for ajax preflighted mode.

**Comment by amnesia7** [comment]
@christophlingg I was just wondered if JSONP was going to be added at some point.
It looks above like this has been moved to milestone 0.2.1 but milestone issues for 0.2.1 doesn't seem to mention this unless I've misinterpreted it.

**Comment by christophlingg** [comment]
This issue is not assigned to any milestone. as far as I know we do not need to add any header as the  preflight mode is not used for simple GET requests like the photon api calls.

Neither I understood why we need to support JSONP, can you describe your problem?

**Comment by Hacktivista** [comment]
@christophlingg Preflight is not really needed in modern servers (as you can see here: http://stackoverflow.com/a/16945321/2026769), still is implemented in all commonly used javascript libraries when performing Ajax request.

I do wonder why nobody else asked about this extremely needed request response (in order to work smoothly).
