### ISSUE TITLE
enhance nominatim database before starting an import

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#138]
As mentioned in https://github.com/komoot/photon/issues/134#issuecomment-70416157 nominatim has some problem with assigning german cities correctly. Apparently we can run a small script that corrects this assignments.

**Comment by christophlingg** [comment]
@lonvia, you mentioned this idea, could you help me a little bit to implement it?

I presume the idea is to save `place=city` in the `extratag` column of `placex` for the [special cities in germany](https://wiki.openstreetmap.org/wiki/Liste_kreisfreier_St%C3%A4dte). Do we need to trigger a reindex of nominatim then?

**Comment by christophlingg** [comment]
Having a look a [this case](http://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=31906497) I am wondering if we could enhance the nominatim exporter. If we get an address entry that matches with one of the hard codes osm ids, I assign it automatically as city. I think that would work, but it's also a bit rough and will only work for germany. 

Maybe it's better to fix it at nominatim, taking into account the place:de tag maybe. Iam willing to fix that but don't know yet where to start ;-)

**Comment by lonvia** [comment]
Just adding `place=city` to `extratags` would do the trick, no reindexing required. I was thinking to simply maintain a list of the Kreisfreie Städte and look them up by name to find the matching entry and change extratags. Roughly, it should work like this (I have tested with only one city, use at your own peril):

1. Find name id: `select word_id from word where word_token = ' ' || make_standard_name('<city name>')`
2. Find the place: `select p.place_id from search_name s, placex p where name_vector @> array[<word_id>] and s.country_code = 'de' and s.search_rank = 12 and and p.class='boundary' and s.place_id = p.place_id`
3. Update extratags: `update placex set extratags = extratags || 'place=>city' where place_id = <place_id>`

Berlin, Hamburg and Bremen are a bit more tricky, because we need to interfere state and city from the same relation. I'm not sure if the import script is prepared for that. Maybe you could try testing with a Berlin relation with place=city set. (Also rank_search needs to be 8 for them in above query.)

**Comment by christophlingg** [comment]
Thanks for the information, I will test it soon and share my findings. Good to know that you can change extratags without harm, I thought it could demolish the index.

**Comment by christophlingg** [comment]
My nominatim setup finished, so I could get back to missing city assignments in Germany. I created a few test cases and opted for solution that includes manually selected cities.

This is the commit in question: https://github.com/komoot/photon/commit/6cc73588529f07ebf2623da79cc961c0fd80fbd2

It may take some days until the import is finished and we can start to evaluate the results.

**Comment by christophlingg** [comment]
with curated exceptions we could assign german cities exactly, we can repeat that for other countries if needed
