### ISSUE TITLE
Buildings with multiple house numbers

### ISSUE THREAD

**Issue by hope15** [komoot/photon#139]
If a building has multiple house numbers, e.g. 
http://www.openstreetmap.org/way/154469124#map=19/47.14587/10.57187 
the house numbers cannot be found.

**Comment by christophlingg** [comment]
how does nominatim deal with such cases @lonvia? If nominatim can't help us we could create multiple entries by our own.

**Comment by lonvia** [comment]
Multiple housenumbers like that are unlikely to be ever supported by Nominatim because this kind of tagging is too fragile (what if there actually are house numbers with commas and semicolons). IMO tagging separate entries is the way to go.

For photon, it's fairly easy to deduplicate those numbers in the exporter (although I'm not sure if we ever anticipated creating more than one entry per Nominatim place), so I suggest to go down that road. If you want to support this, you should probably also look into interpolations on buildings. See https://trac.openstreetmap.org/ticket/4789
