### ISSUE TITLE
Addr:place tag in the result list

### ISSUE THREAD

**Issue by mjuen** [komoot/photon#147]
It would be nice if there would be an option to also get the `addr:place` tag in the result list.

E.G. with an optional `GET` parameter in the search request.

**Comment by christophlingg** [comment]
at the moment we ignore this information, you can neither search for it nor can we return it in the search result.

I am not aware of how important it really is, but this tag seems to be used quite often: 

 - http://wiki.openstreetmap.org/wiki/Key:addr:place
 - http://taginfo.openstreetmap.org/keys/?key=addr%3Aplace#overview

Sounds like a useful enhancement

**Comment by lonvia** [comment]
addr:place is like addr:street mainly useful for matching. Normally you would tag an address like 'Hauptstr. 3, Berlin' as `addr:housenumber=3, addr:street=Hauptstr`. If you have a tiny village with no street names that doesn't work, so you would tag for example the address 'Entenhausen 3' as `addr:housenumber=3, addr:place=Entenhausen` to make it clear that there is no street in the address.

To make a long story short, addr:place is already implicitly returned in the city part when Nominatim was able to match it with something useful, so I'm not exactly sure what information could be gained. @hope15, could you clarify for what you need addr:place?

**Comment by hope15** [comment]
At the moment it's hard to identify if the given street name is really the name that matches with the house number. That is because if the street name is missing (+ the `addr:place` tag set) the next available street name in the immediate vicinity is taken and returned in the `addr:street` tag.

Example:
http://photon.komoot.de/api/?q=nauders%20435,%20nauders
http://www.openstreetmap.org/#map=19/46.89614/10.50071

**Comment by lonvia** [comment]
That is just a case of outdated data. This address has received the addr:place tag only 2 days ago while the photon database is a few weeks old.

Photon is using the same address processing as Nominatim, the search engine on the osm.org frontpage and you ca see that it has correctly taken into account the new addr:place tag: http://nominatim.openstreetmap.org/details.php?place_id=109487524 Photon will have the same address when its database gets updated next time.

**Comment by amnesia7** [comment]
Aren't the osm changes made available relatively quickly? 
Does photon not pick the changes up and updating the database with them once released?

**Comment by hope15** [comment]
15 days have passed and it's still the same result...

How will the result look like if it's finally updated?

**Comment by christophlingg** [comment]
photon.komoot.de is not updated continously, the server is not big enough to handle photon and nominatim at the same time.

**Comment by amnesia7** [comment]
@christophlingg sorry to comment on a closed issue but I think elasticsearch can be used as a data store rather than just as a search index.
Would that mean that you wouldn't need your server to have both photon and nominatim giving you a bit more space for updates etc and allow nominatim patches/updates to be added more often directly into the elasticsearch data store?
I don't know but would this make it less complicated since it would just be one data store rather than two.

**Comment by hope15** [comment]
I have also one more question to @lonvia. The problem here in Austria is that we have many villages that have different names for districts e.g. `Dorf` but the street does not have a name. Without the `addr:place` tag it is not possible to tag houses in those villages correctly and get useful information from photon. Assuming that the city tag is the same as the place tag is here not possible.

Is there any better solution than adding this tag to the result list?

**Comment by lonvia** [comment]
@hope15 Hmm, I see. So that gets us back to the discussion if suburbs should be included, i.e. in your case the part of the town that give the houses their 'place' name.

This actually makes me wonder if the schema of fixed fields isn't too restrictive to get all the different addressing schemas of the world in. In this case, the addr:place part would actually fit well into the street column but it would be necessary to somewhere retain the information that this is not a street.

**Comment by christophlingg** [comment]
@amnesia7 photon is not going to able to replace nominatim as it does a huge job in processing the data. technically a elasticsearch only data storage sounds very interesting and maybe the guys over at pelias will create something cool, but I assume it will take some time...

**Comment by hope15** [comment]
I like that idea, what if we simply add a `*` in front of the result in the `addr:street` tag if there's only the `addr:place` tag available?

For example:

`photon.komoot.de/api/?q=pfunds, dorf 63`

![unbenannt](https://cloud.githubusercontent.com/assets/7404431/7003003/e1c5f628-dc53-11e4-8898-a4d76be9d587.PNG)

**Comment by sdole** [comment]
prefixing a result will mean that all users will have to change code to
remove prefix. possibly a small change, but, still a change.

On Mon, Apr 6, 2015 at 4:57 AM, Marcel <notifications@github.com> wrote:

> I like that idea, what if we simply add a * in front of the result in the
> addr:street tag if there's only the addr:place tag available?
>
> For example:
>
> photon.komoot.de/api/?q=pfunds, dorf 63
>
> [image: unbenannt]
> <https://cloud.githubusercontent.com/assets/7404431/7003003/e1c5f628-dc53-11e4-8898-a4d76be9d587.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/komoot/photon/issues/147#issuecomment-89997710>.
>



-- 
President  |  Genvega Inc.  |  www.genvega.com  |  tel: 630.290.2561

**Comment by hope15** [comment]
Sure, they will have to change something if they want to support the `addr:place` tag.

`addr:street is set`  | `addr:place is set ` | `Old addr:street result`  | `New addr:street result`  |
------------- | ------- | ------------ | --------------- |
true| false | `addr:street` | `addr:street` |
true| true | `addr:street` | `addr:street`|
false | false | Empty | Empty|
false | true | Empty | `'*' + addr:place`

Everything stays the same, except if **only** the `addr:place` is set. Before you simply didn't get anything back in `addr:street` tag.

But I see your point. What if we come back to the idea with the `GET` - Parameter

`photon.komoot.de/api/?q=pfunds, dorf 63&placeStreet=1`

If it's included you get the results like shown above, if not, you'll get the old result.

So everybody is happy and we won’t brick anything...

**Comment by prasadrajuv** [comment]
pls look at addr:place with addr:district addr:subdistrict in next modification. location in java file has to change while import and search code. pls improve documentation not show all options

**Comment by lonvia** [comment]
We now return more address fields including district. That should solve the problem for all listed cases.
