### ISSUE TITLE
Finetuning, adding house number decreases relevance significantly

### ISSUE THREAD

**Issue by karussell** [komoot/photon#187]
Somehow a house number makes problems. See [this query without](http://photon.komoot.de/api/?q=rochlitz%20seminarstrasse&debug=true) vs. [this with](http://photon.komoot.de/api/?q=rochlitz,%20seminarstrasse%208&debug=true) the '8'. If '8' is included the results do not make sense.

**Comment by christophlingg** [comment]
the postcode of the result in styria starts with an eight: `8045`, probably it's because of that. but it is only a partial match in comparison with `rochlitz` of the first result list. complete matches have higher priority than partial matches. the inverse term frequency might be the reason why the wrong result appears...

**Comment by karussell** [comment]
Yes, very strange. Another strange thing is [when the space is missing](http://photon.komoot.de/api/?q=rochlitz,seminarstrasse&debug=true) and instead a comma is used => no results.

**Comment by lonvia** [comment]
House number searches should work get a better relevance score with #580. Missing house number is still an issue though but we have #204 for that. So closing this issue.
