### ISSUE TITLE
Bypass Nominatim and import OSM data directly

### ISSUE THREAD

**Issue by stephane-bastian** [komoot/photon#212]
Hi,
First of all, kudos to the team for this great product.

I would like to know what it would take to bypass Nominatim and import OSM data directly (like the Pelias project) ? 
The main and immediate benefit is that we won't have to install Nominatim anymore to import OSM data.
Another far-fetched benefit is that it could be the first baby step to abstract Photon away from OSM and import data from other sources as well. (OpenAddresses, Geonames, BAN)

Any ideas or comments? 
Thx

**Comment by christophlingg** [comment]
you can already import json files to photon that follows a specific structure. so it would be easy to render osm objects or any other source to this json structure.

Nominatim is essential for OSM data because we use it to complete single osm objects, like house numbers. Nominatim detects to which street a house number belongs, and to which city, state and country. these relations are important if you want to search for a full address `10 downing street london`

**Comment by stephane-bastian** [comment]
Hi Christoph,

I understand that Nominatim does most of the leg work when importing raw OSM data. But based on your experience, what would it take to replace Nominatim by a custom importer, parsing raw osm data and 'reconciliating' hirarchical information such as city, state and such? I guess would also have to take into account synonymous for various words (street, boulevard, etc..) in different languages.
1) Do you think it would be valuable?
2) Would you estimate this to be a one week project, or a one month project ? more?

**Comment by karussell** [comment]
It will take you definitely more than one month (if from one person). Also you'll still need an optimized storage for spatial data processing like postgres or a custom one or ES itself

**Comment by christophlingg** [comment]
Mapzen is working on an importer for their search which is based on ES only, FYI. And yes it will take quite a lot of time and iterations to have osm data under control. Continuous updates makes it even more tricky.

**Comment by karussell** [comment]
Won't fix
