### ISSUE TITLE
Hyphenated housenumber are not always found

### ISSUE THREAD

**Issue by moltamas93** [komoot/photon#265]
Address don't always seem to be found in photon if it spans multiple housenumber with a hyphen. It seems that only addresses with name are found, plain housenumbers are not found. Nominatim seems to find all addresses regardless.

Not found by photon: József utca 48-50
http://nominatim.openstreetmap.org/search.php?q=Budapest+J%C3%B3zsef+utca+48-50
http://photon.komoot.de/api/?q=Budapest+J%C3%B3zsef+utca+48-50

Found by photon: Budapest Kazinczy utca 23-27
http://nominatim.openstreetmap.org/search.php?q=Budapest+Kazinczy+utca+23-27
http://photon.komoot.de/api/?q=Budapest+Kazinczy+utca+23-27

**Comment by hbruch** [comment]
The underlying cause is the same as in issue #221: housenumbers currently are not analyzed when indexed, so 48-50 is not split. However, when querying, ES standard analyzer is used to tokenize the query string, resulting in tokens 48 and 50.

As photon filters query results that have either no housenumber at all, an exact match or a name, only those hyphenated housenumbers having a name are found.

I‘m working on a fix.

**Comment by hbruch** [comment]
Is fixed via #288: 
`/api/?q=Budapest+J%C3%B3zsef+utca+48-50` now returns József utca 48-50.
