### ISSUE TITLE
Reverse geocoding max limit hard coded to 50 ?

### ISSUE THREAD

**Issue by R1im** [komoot/photon#340]
I cant seem to get limit work.
http://photon.komoot.de/reverse/?lat=58.522&lon=31.26&limit=4999&radius=2.1

tried it on local photon 0.3 and still - only 50 results max

**Comment by lonvia** [comment]
The limit is hard-coded to maximum of 50 [here](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/query/ReverseRequestFactory.java#L86). That's intentional as the reverse function is meant to give you the address of a given position. So one or two results would even be enough under normal circumstances.
