### ISSUE TITLE
Location-aware search rarely works

### ISSUE THREAD

**Issue by gjedeer** [komoot/photon#375]
We're trying to debug the search results in Acastus Photon here:

https://github.com/gjedeer/Acastus/issues/7

As @k3b noticed, searching for a Starbucks in Berlin returns no relevant results, the nearest one being in Canada:

https://photon.komoot.de/api/?q=starbucks&lat=52.3879&lon=13.0582
https://photon.komoot.de/api/?q=starbucks&lat=52&lon=13

He was able to get good results with a non-location-aware query:

https://photon.komoot.de/api/?q=berlin+starbucks

**Comment by simonpoole** [comment]
This seems to be a general issue with location bias not working if there is no country term https://photon.komoot.de/api/?q=starbucks%20deutschland&lat=52.3879&lon=13.0582 for example will work (more or less, see some other issues with location bias that are being worked on) as expected

**Comment by gjedeer** [comment]
🤔 so if I reverse-geocode the location to extract country name, then append it to the end of search it may work? A bit backwards but it may work, thank you!

**Comment by simonpoole** [comment]
I spent some time today analysing the behaviour and believe that the cause for the issue is now understood.

The root cause are underlying OSM data errors that cause the nominatim importance value to be greater than it should be, for example by setting the wikipedia tag to the corporate wikipedia page instead of using the brand:wikipedia tag.

In photon the imported importance value has a large influence on the scoring, as the distance derived factor will only sort correctly for roughly similar scores this leads to hits that are very far away, but have larger importance to be returned as top matches.

Besides fixing the data which should be done in any case, one possible further fix could be to weight the importance less than it is now (removing it completely gives the correct results in your example, but given we have this information and in general it is helpful, that is not really a solution).

**Comment by lonvia** [comment]
`location_bias_scale` can be used to weigh the impact of importance. E.g. in the above example:

https://photon.komoot.de/api/?q=starbucks&lat=52.3879&lon=13.0582&location_bias_scale=10

The higher the scale the more important it is that the result is close to the given location.

**Comment by gjedeer** [comment]
`location_bias_scale` should do the trick in the case of Acastus, thank you @lonvia ! I didn't even know that importance is being taken into account, I see there's use for that in autocomplete on websites.

Anyway. Just tagged a new release of Acastus Photon and damn, the search results are actually good now. Thank you @lonvia  and @simonpoole
