### ISSUE TITLE
postcode value with two pipe-separated numbers for index entry

### ISSUE THREAD

**Issue by BloodyMettle** [komoot/photon#437]
[This query](https://photon.komoot.de/api?q=Sch%C3%B6nhauser%20Allee/Bornholmer%20Stra%C3%9Fe)  for a bus/tram stop in berlin returns several results with 
`"postcode": "10437|10439"` 
The two postcode areas are next to each other, but the stop is inside 10439 and there on the far side of 10437. There is no connection or relation for this stop that should result in this and I have never seen a piped double postcode entry in a German address. All related OSM entries i could find have the correct postcode 10439.
It seems like there is some bug in the generation of this index entries. I did not run index creation locally and don't have access to any database, but I know that the index has the same error in at least one other instance that was created via photon. 
If it's not a bug but based on wrong OSM data, it would be nice to know what's the causing error, otherwise it would be interesting to know how this was generated and if it can be fixed. 
Thanks!

**Comment by lonvia** [comment]
Postcodes for objects that don't have one tagged directly get a guessed postcode according to an elaborated schema which is explained a bit [in this blog post](https://www.openstreetmap.org/user/lonvia/diary/43143). This all happens in the preprocessing step of Nominatim. So Photon is not the one with the bug in such case but rather Nominatim. That just as a general comment.

For the concrete problem: if the odd postcode cannot be found on the OSM object directly, it likely comes from a badly tagged object around. To find them, I generally use taginfo and Overpass as follows:

* Search for the value in taginfo: https://taginfo.openstreetmap.org/search?q=10437#values (taginfo doesn't support searching for values with a '|', so we search for half the value)
* Find the one which points to a postcode tagging: https://taginfo.openstreetmap.org/tags/postal_code=10437%7C10439
* Click on the Overpass link in the upper right corner: https://overpass-turbo.eu/?w=%22postal_code%22%3D%2210437%7C10439%22+global&R

And you have the culprits. I'd just remove the offending postcodes from the three objects. We have postcode areas in Germany that are working nicely.

NB: There is an actual bug here. Nominatim should have preferred the postcode areas over some random nearby postcodes. We have an open issue for that at https://github.com/openstreetmap/Nominatim/issues/1209.
