### ISSUE TITLE
Housenumber issue when searching in non-default language

### ISSUE THREAD

**Issue by kostjerry** [komoot/photon#496]
It would be helpful to add the **housenumber** field to the all lang-specific collectors.

For now the address search in other langs miss many addresses.
I have tested the address "Тростянецька 3" in Kyiv (Ukraine) with default lang **uk** and additional langs **ru** and **en**.
When requesting "Trostianetska 3" in **en**, the photon don't find this address.
I have solved this issue by adding all langs manually in mappings.json and rebuilding jar-file.
```
...
"housenumber": {
	"type": "text",
	"index": true,
	"analyzer": "index_housenumber",
	"search_analyzer": "standard",
	"copy_to": [
		"collector.default",
		"collector.uk",
		"collector.ru",
		"collector.en"
	]
},
...
```
I believe this could be done automatically from the code, but unfortunately I was not able to achieve the desired result by this way.

**Comment by lonvia** [comment]
This is a really good catch but the issue is not confined to house numbers. Any mixing of languages in the query will go wrong. So I went for a more broad approach in #538. Could you give that a try and see if it resolves your issues without making other queries worse? The PR can be run on an existing database. It only changes the query to ES.

**Comment by lonvia** [comment]
Searching the address in English now works on the demo server. So I assume this is fixed.
