### ISSUE TITLE
Deprecation plan for API on photon.komoot.de

### ISSUE THREAD

**Issue by JorgenG** [komoot/photon#516]
In October 2020 the API was made available on photon.komoot.io as the long-term home of the API. The old API still redirects to the .io domain. Over the next year this will gradually be deprecated.

Currently the redirects are handled by the underlying Photon server. To monitor the usage and safely deprecate the old URL, we will be switching the redirection to a new server, however this server will not provide CORS.

In other words, **there will be a breaking change**, planned to go live on **Thursday 27th November**. This breaks CORS for web-pages which directly sends API requests from the browser. The fix is to reconfigure API requests to go to the new domain `photon.komoot.io`. (All other API requests will still work (Due to redirects) towards the `photon.komoot.de` domain, however we highly suggest switching as soon as possible.)

We are planning to terminate the redirect fully on 1st of July 2021, at which point only requests to `photon.komoot.io` will work.

**Comment by simonpoole** [comment]
I'm slightly concerned that komoot isn't aware of the controversy surrounding .io domains. It would seem not to be a good idea switching to something which has besides being ethically questionable, has an unsure future. And I'm saying that as somebody that currently has an .io domain which I haven't been able to move off from, so I'm feeling the same pain.

**Comment by rory** [comment]
The issue is that `.io` domains are for the "British Indian Ocean Territory", and fees go to support the British military occupation, which has carried an effective genocide of an entire people (the Chagossians). A CIA black site is rumoured to be operating there. Recently the United Nations' International Court of Justice has ruled the occupation illegal.  [read more](https://www.bbc.com/news/uk-47358602). This project doesn't have a Code of Conduct, this isn't explicitly discouraged.

See more:
 * https://en.wikipedia.org/wiki/Expulsion_of_the_Chagossians
 * https://www.chagossupport.org.uk/

----
I don't use the current API endpoint, but 4 days announcement of a breaking change seems a bit rushed.

**Comment by karussell** [comment]
> has an unsure future.
> ...
> I don't use the current API endpoint, but 4 days announcement of a breaking change seems a bit rushed.

This is a free service and no one is paying for this. So I don't think there are any requirements here. This endpoint also has no uptime guarantees - but again, it is a contribution from komoot and I'm thankful for this.

Surely there are commercial geocoding offerings with photon behind that give you a contract & guarantees. (And at least the one offerings that I know also has a `.com` domain ;) )

**Comment by debuglevel** [comment]
Even though it is a free service, I always wonder what is the reason of not redirecting requests from an old domain to a new domain for the next five years?
