### ISSUE TITLE
Avoid hardcoding of “search_ngram” at PhotonQueryBuilder

### ISSUE THREAD

**Issue by JinIgarashi** [komoot/photon#555]
While we modified Photon's source code for adopting to search by Japanese language, we found this issue to do hardcoding "search_ngram" for all languages at PhotonQueryBuilder.

https://github.com/komoot/photon/blob/2bbce026b58b44d33388d9bca0fe1747c32a9933/src/main/java/de/komoot/photon/query/PhotonQueryBuilder.java#L60-L73

In our repository, we changed source code like this to use our Japanese analyzer when it comes to `ja` and `ja_kana`.

https://github.com/MIERUNE/photon/blob/e3c93b89335d5e9ef1513cd053f49f54ed0ca6cb/src/main/java/de/komoot/photon/query/PhotonQueryBuilder.java#L60-L80

```java
            Fuzziness fuzziness = Fuzziness.ONE;
            String analyzer = "search_ngram";
            ArrayList<String> ja_languages = new ArrayList<String>(Arrays.asList("ja", "ja_kana"));            
            if (ja_languages.contains(language)){
                fuzziness = Fuzziness.ONE;
                analyzer = "ja_ngram_search_analyzer";
            }
            BoolQueryBuilder builder = QueryBuilders.boolQuery()
                    .should(QueryBuilders.matchQuery("collector.default", query)
                                .fuzziness(fuzziness)
                                .prefixLength(2)
                                .analyzer(analyzer)
                                .minimumShouldMatch("-1"))
                    .should(QueryBuilders.matchQuery(String.format("collector.%s.ngrams", language), query)
                                .fuzziness(fuzziness)
                                .prefixLength(2)
                                .analyzer(analyzer)
                                .minimumShouldMatch("-1"))
                    .minimumShouldMatch("1");

            query4QueryBuilder.must(builder);
```

But our modification is also hardcoding, I think it is not the best solution. Is there a better way to solve this issue?

**Comment by lonvia** [comment]
I'm wondering... do we even need to specify the analyser in that part of the code? I'd expect that it uses the analyser from the mapping.json if none is given. And with #552 merged, it should be the right one.

That said, with merging of #538 if isn't really easily possible anymore to have different analysers for the different 'collector.*.ngrams' indexes because of [this cross-field MultiMatch](https://github.com/komoot/photon/blob/d8263d958520329ee8c1f19f95f59db8b49bb52c/src/main/java/de/komoot/photon/query/PhotonQueryBuilder.java#L76). It doesn't quite work as expected when the fields have different analysers.

**Comment by JinIgarashi** [comment]
@lonvia Thank you for the comment. I reverted my source code of `PhotonQueryBuilder`, and I found it is working with Japanse searching. While I was developing I did many try and errors, I though there was some effects after changes of PhotonQueryBuilder. Let me close this issue.
