### ISSUE TITLE
Address search in error if "bis" in number

### ISSUE THREAD

**Issue by sylvain-m** [komoot/photon#614]
Hi,

Even if the addresses are present in OSM, searches with a `bis` in the number are unsuccessful.
Here is an example: `11 bis Rue Normandie Maine 53370 Gesvres` ([OSM Node](https://www.openstreetmap.org/node/9255889710))

- with `bis` = no result
https://photon.komoot.io/api/?q=11%20bis%20Rue%20Normandie%20Maine%2053370%20Gesvres

- without `bis` = result ok
https://photon.komoot.io/api/?q=11%20Rue%20Normandie%20Maine%2053370%20Gesvres

This is a recent address node, but I've had this kind of error with older addresses, and in any case, if the `bis` is not present in OSM, it shouldn't override a possible result without the `bis`.

**Comment by lonvia** [comment]
The Photon database is only updated once a week, so I can't comment on the specific example before next Tuesday. That is why the first query currently doesn't produce results. Photon can skip over one missing term (e.g. "bis") just fine but not over two ("11" and "bis" here). So it can't get you just the road as a result. This is not possible to fix unless we add some very elaborate guessing about what is the house number here and should be skipped. And that is a much harder problem than it looks to be at first glance.

Also, the 'bis' house numbers can be an issue when searching because there are two variants in the OSM database with space ("11 bis") and without ("11bis"). You need to search for the variant as it was entered in OSM or things won't work. Needless to say that this is not ideal.

**Comment by sylvain-m** [comment]
Sorry, you're right: I just tested with an [older address](https://www.openstreetmap.org/node/3670794379), and Photon finds even with the bis.
https://photon.komoot.io/api/?q=9%20bis%20Rue%20Georges%20Brassens%2061250%20Valframbert

I was misled because in fact I had a search with Nominatim that did not work.
And indeed, if I try with Nominatim on this old address, it still doesn't work : 
[https://nominatim.openstreetmap.org/ui/search.html?q=9+bis+Rue+Georges+Brassens+61250+Valframbert](https://nominatim.openstreetmap.org/ui/search.html?q=9+bis+Rue+Georges+Brassens+61250+Valframbert)
I'm going to inform them (even if I understand the difficulty of managing special cases)

**Comment by lonvia** [comment]
Closing here. The examples above work now. There are things that could be improved with respect to housenumbers but nothing particularly actionable for this case.
