### ISSUE TITLE
Initial and update of interpolations is different

### ISSUE THREAD

**Issue by hendrikmoree** [komoot/photon#632]
For initial import of interpolations the original doc is imported. See: https://github.com/komoot/photon/blob/ce84ef47ed85298bd9986d005523a685b7636cc6/src/main/java/de/komoot/photon/nominatim/NominatimConnector.java#L256

On update it updates the documents returned from `getDocsWithHousenumber()`
https://github.com/komoot/photon/blob/ce84ef47ed85298bd9986d005523a685b7636cc6/src/main/java/de/komoot/photon/nominatim/NominatimConnector.java#L158

I think the update part is right in this case. But not complete sure.
It seems the initial import seems to create documents without a centroid added to it. The centroid however is created in `getDocsWithHousenumber()` for every housenumber

For example after an intial import I got an empty centroid for this one https://www.openstreetmap.org/way/251306600. Should empty centroid's even be allowed?

**Comment by lonvia** [comment]
The import uses `getDocsWithHousenumber()` too. It is called in the import thread. See: https://github.com/komoot/photon/blob/719df8ce10ccb10c20165119a525042225b09b17/src/main/java/de/komoot/photon/nominatim/ImportThread.java#L34

Nominatim has a couple of 'dead' interpolations in its table. They don't have the startnumber set. Photon used to import them, too. This was fixed in #635. I suspect that this is what you are seeing. Note that your example way doesn't have any interpolation numbers between 126 and 128.

**Comment by lonvia** [comment]
Assuming this fixed by #635.
